# Copyright 2020 Carnegie Mellon University. All Rights Reserved. See LICENSE.md file for terms.

version: '3.8'

networks:
  ghosts-network:
    driver: bridge

services:
  mongo:
    image: mongo
    container_name: ghosts-mongo
    ports:
      - '32770:27017'
    networks:
      - ghosts-network
    restart: always
    volumes:
      - ./_data:/data/db
  ghosts-animator:
    image: dustinupdyke/ghosts-animator:0.8.5
    container_name: ghosts-animator
    ports:
      - '5000:5000'
    networks:
      - ghosts-network
    restart: always
    volumes:
      - ./_output:/output
