# Copyright 2020 Carnegie Mellon University. All Rights Reserved. See LICENSE.md file for terms.

version: '3.8'

networks:
  ghosts-network:
    driver: bridge

services:
  mongo:
    image: mongo
    container_name: ghosts-mongo
    ports:
      - '27017:27017'
    networks:
      - ghosts-network
    restart: always
    volumes:
      - ./_data:/data/db
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongo
    networks:
      - ghosts-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=ghosts-mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=scotty@1
    ports:
      - '8081:8081'
    volumes:
      - ./_data_express:/data/db
  ghosts-animator:
    image: dustinupdyke/ghosts-animator:0.8.6
    container_name: ghosts-animator
    ports:
      - '5000:5000'
    networks:
      - ghosts-network
    restart: always
    volumes:
      - ./_output:/output
